<?php
declare(strict_types=1);

namespace App\Core;

/** Values from private/config.php (written by the web installer). */
final class Config
{
    private static ?array $data = null;

    public static function load(?array $data): void
    {
        self::$data = $data;
    }

    public static function installed(): bool
    {
        return self::$data !== null && !empty(self::$data['installed']);
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        $node = self::$data ?? [];
        foreach (explode('.', $key) as $part) {
            if (!is_array($node) || !array_key_exists($part, $node)) {
                return $default;
            }
            $node = $node[$part];
        }
        return $node;
    }

    public static function all(): array
    {
        return self::$data ?? [];
    }

    public static function write(array $data): bool
    {
        $php = "<?php\n// Generated by the Captains of Jawai installer. Keep this file private.\nreturn " . var_export($data, true) . ";\n";
        $ok = file_put_contents(CONFIG_FILE, $php, LOCK_EX) !== false;
        if ($ok) {
            @chmod(CONFIG_FILE, 0640);
            if (function_exists('opcache_invalidate')) {
                @opcache_invalidate(CONFIG_FILE, true);
            }
            self::$data = $data;
        }
        return $ok;
    }
}
